# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 21:42
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_questions_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='questions',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
