# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20170423_2142'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='questions',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='user',
            new_name='profile',
        ),
    ]
