# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20170425_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='tag',
            new_name='tags',
        ),
    ]
